name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Code check and tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: pip install pipenv
      - name: Check code formatting
        uses: pre-commit/action@v2.0.3
      - name: Prepare docker-compose override file
        run: |
          ln -s docker-compose.override.local.yml docker-compose.override.yml
      - name: Check env vars coniguration
        run: |
          scripts/check_envvars.sh
      - name: Export the env variables file
        run: |
          cp .env.example .env
          eval $(egrep "^[^#;]" .env | xargs -d'\n' -n1 | sed -E 's/(\w+)=(.*)/export \1='"'"'\2'"'"'/g')
      - name: Pull docker containers
        run: docker-compose pull
      - name: Build and run docker containers
        run: |
          docker-compose up -d --build
      - name: Run unit and integration tests
        run: |
          docker-compose run app python manage.py test -v2 qfieldcloud

      - name: "failure logs"
        if: failure()
        run: |
          docker-compose logs
